# Generated by Django 5.2.17 on 2026-09-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
