# Generated by Django 5.2.17 on 2026-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customerprofile_health_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='degrees',
            field=models.CharField(blank=True, default='MBBS, MD', max_length=255),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='experience_years',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='consultation_type',
            field=models.CharField(default='Online & In-Person', max_length=50),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='credential_status',
            field=models.CharField(default='Verified', max_length=50),
        ),
    ]
