# Generated by Django 5.2.17 on 2026-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
