# Generated by Django 5.2.17 on 2026-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customerprofile_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
