# Generated by Django 5.2.17 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customerprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar_image',
            field=models.FileField(blank=True, upload_to='profile_photos/'),
        ),
    ]
