# Generated by Django 5.2.17 on 2026-09-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIQueryLog',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='thread_type',
            field=models.CharField(choices=[('Customer-Seller', 'Customer-Seller'), ('Customer-Provider', 'Customer-Provider'), ('Provider-Seller', 'Provider-Seller'), ('Seller-Courier', 'Seller-Courier')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant1', 'participant2', 'thread_type'), name='unique_conversation_pair'),
        ),
    ]
